### ISSUE TITLE
Do you have a whitelist please? The store page comes up blank

### ISSUE THREAD

**Issue by danprice142** [ljorge705/ljorge705.github.io#1]
Please say you do, im from the UK and ive been looking for TSnavigator and IPTV everywhere if not can you send me the UWP/APPX Please?

**Comment by ljorge705** [comment]
yes, sure, but the links are of the original tvnavigator and TIPV, you can buy tnavigtor here https://www.tgameseapps.net/buytn/
and this is the official forum https://tgameseapps.flarum.cloud/

I recommend these emulators and apps: https://gamr13.github.io/    https://nun-z.github.io/

**Comment by danprice142** [comment]
Do i need to send you my email for your whitelist? or can you send me a googledrive link fot the original ts and TIPV? IM ALREADY IN Doms discord for https://gamr13.github.io/ but they dont do TS and PITV.
